"""empty message

Revision ID: 16fb5c3a939e
Revises: 
Create Date: 2023-06-16 00:55:26.293229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fb5c3a939e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('user_images', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('data_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('emails',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_email', sa.String(length=128), nullable=False),
    sa.Column('view', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('view', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_table('emails')
    op.drop_table('users')
    # ### end Alembic commands ###
